### ISSUE TITLE
结果融合的一个问题

### ISSUE THREAD

**Issue by fys445089968** [LiuFG/Camera-Lidar-Fusion-ROS#1]
the origin idea is to detection on /ROIpicture, but the result is not very good. /ROI2D is results of the 3D-2Dbox。请问这个是最开始想法是lidar在图像上形成ROI，然后在ROI上用yolo检测结果不太好的意思吗。

**Comment by LiuFG** [comment]
> the origin idea is to detection on /ROIpicture, but the result is not very good. /ROI2D is results of the 3D-2Dbox。请问这个是最开始想法是lidar在图像上形成ROI，然后在ROI上用yolo检测结果不太好的意思吗。

是这样的，可能需要用ROI的图像重新训练yolo。anyway，感觉这样的方案很naive了

**Comment by fys445089968** [comment]
读到好多类似的论文，看他们实验结果还可以呀。好几篇还是sci，不知道咋回事。同样方法差距这么大。。

**Comment by LiuFG** [comment]
第一，可能是ROI的质量和使用的方式不同，相关的顶会论文基本都是3年的？我这个确实比较naive，只是用ros节点生硬拼接，不是那种端到端训练的。
第二，你说的sci的论文不知道是哪篇？做感知的，发sci很少吧，质量存疑

**Comment by fys445089968** [comment]
使用方式是有些区别，我看的这篇是把roi做了后期融合，还加了一些trick，只是大体思路还是这样。可能做一些调整效果确实会提高很多。
