### ISSUE TITLE
Could you give one general introduction on how to fusion the image and point cloud

### ISSUE THREAD

**Issue by 1770031555** [LiuFG/Camera-Lidar-Fusion-ROS#4]
cloud you give one general blog introduce the method of fusion the two dataset .

**Comment by ryontang** [comment]
my question is also related to this, could you share your thesis or give some introduction about your method on associate the image and point cloud object.

**Comment by 1770031555** [comment]
> my question is also related to this, could you share your thesis or give some introduction about your method on associate the image and point cloud object.

HHHH, my problem has been resolved , you could directly edit the source codes from the author , and thus you will find the answer . 
You could use darknet_ROS to generate bounding box and object type , and thus you could fusion the two signals together successfully .
But why 3 chinese people chat via en ?

**Comment by lovesuiyue** [comment]
你好,能分享一下作者的这个代码里用到的kitti数据集吗? @ryontang @1770031555 @
