### ISSUE TITLE
Error reading CAMERA02/CAMERA03 calibration

### ISSUE THREAD

**Issue by lovesuiyue** [LiuFG/Camera-Lidar-Fusion-ROS#6]
![2021-12-11 19-46-01 的屏幕截图](https://user-images.githubusercontent.com/87158793/145675366-b33cf26d-a8ea-44df-be70-c03c079520cb.png)
这个有遇到吗?

**Comment by namritaansh02** [comment]
make sure to keep that calib_cam_to_cam.txt file inside dataset/2011_09_26/2011_09_26_drive_0018_sync

**Comment by lovesuiyue** [comment]
OK
